In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,f1_score
from sklearn.model_selection import train_test_split





df = pd.read_csv("Iris.csv")

# print(df.head())

# for detection of Null count in columns
# print(df.isnull().sum())

# fill null value with first non null value
# df = df.fillna(method="ffill")

# for fill categorical data
# df['column_name'] = df['column_name'].fillna(df['column_name'].mode()[0])

# fill null values with mean of the columns
# df['column_name'] = df['column_name'].fillna(df['column_name'].mean())


label_encoder = LabelEncoder()
df['Species'] = label_encoder.fit_transform(df['Species'])

df.drop("Id",axis=1, inplace=True)


y = df.pop("Species")

X_train, X_test, Y_train, Y_test = train_test_split(df, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=11)
knn.fit(X_train,Y_train)
pred = knn.predict(X_test)


print(f"Accuracy: {accuracy_score(pred,Y_test)}")
print(f"\nConfusion Matrix\n {confusion_matrix(pred,Y_test)}")
print(f"\n Recall Score: {recall_score(pred,Y_test, average='macro')}")
print(f"\n F1 Score: {f1_score(pred,Y_test, average='macro')}")
print(f"\n Precision Score: {precision_score(pred,Y_test, average='macro')}")

Accuracy: 1.0

Confusion Matrix
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

 Recall Score: 1.0

 F1 Score: 1.0

 Precision Score: 1.0


In [6]:
# KNN without PCA
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,f1_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


df = pd.read_csv("Heart.csv")
y = df.pop("sex")
print(df.head())
# print(df.isnull().sum())


X_train,X_test,Y_train,Y_test = train_test_split(df,y, test_size=0.3, random_state=42)
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train)
pred = knn.predict(X_test)

# Calculate Training Accuracy
train_accuracy = knn.score(X_train, Y_train)
print(f"Training Accuracy: {train_accuracy:.2f}")

print(f"Accuracy: {accuracy_score(pred,Y_test)}")
print(f"\nConfusion Matrix\n {confusion_matrix(pred,Y_test)}")
print(f"\n Recall Score: {recall_score(pred,Y_test, average='macro')}")
print(f"\n F1 Score: {f1_score(pred,Y_test, average='macro')}")
print(f"\n Precision Score: {precision_score(pred,Y_test, average='macro')}")

   age  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  \
0   52   0       125   212    0        1      168      0      1.0      2   2   
1   53   0       140   203    1        0      155      1      3.1      0   0   
2   70   0       145   174    0        1      125      1      2.6      0   0   
3   61   0       148   203    0        1      161      0      0.0      2   1   
4   62   0       138   294    1        1      106      0      1.9      1   3   

   thal  target  
0     3       0  
1     3       0  
2     3       0  
3     3       0  
4     2       0  
Training Accuracy: 0.99
Accuracy: 0.8896103896103896

Confusion Matrix
 [[ 84  16]
 [ 18 190]]

 Recall Score: 0.8767307692307692

 F1 Score: 0.8747787822260487

 Precision Score: 0.8729297544260423


In [7]:
# KNN with PCA
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,f1_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA

df = pd.read_csv("Heart.csv")
y = df.pop("sex")
# print(df.head())
# print(df.isnull().sum())


scalar = StandardScaler()
scaled_df = scalar.fit_transform(df)
Pca = PCA(n_components=2)
df = Pca.fit_transform(scaled_df)

# print(df)

X_train,X_test,Y_train,Y_test = train_test_split(df,y, test_size=0.3, random_state=42)


knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train)
pred = knn.predict(X_test)

# Calculate Training Accuracy
train_accuracy = knn.score(X_train, Y_train)
print(f"Training Accuracy: {train_accuracy:.2f}")

print(f"Accuracy: {accuracy_score(pred,Y_test)}")
print(f"\nConfusion Matrix\n {confusion_matrix(pred,Y_test)}")
print(f"\n Recall Score: {recall_score(pred,Y_test, average='macro')}")
print(f"\n F1 Score: {f1_score(pred,Y_test, average='macro')}")
print(f"\n Precision Score: {precision_score(pred,Y_test, average='macro')}")

Training Accuracy: 0.97
Accuracy: 0.8214285714285714

Confusion Matrix
 [[ 70  23]
 [ 32 183]]

 Recall Score: 0.8019254813703426

 F1 Score: 0.7936536938912235

 Precision Score: 0.7873120121835142
